# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/example.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/example.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16protobuf/example.proto\x12\x07\x65xample\"!\n\x11IncreaseUserCount\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x62\x06proto3'
)




_INCREASEUSERCOUNT = _descriptor.Descriptor(
  name='IncreaseUserCount',
  full_name='example.IncreaseUserCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.IncreaseUserCount.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=68,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='example.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='example.User.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['IncreaseUserCount'] = _INCREASEUSERCOUNT
DESCRIPTOR.message_types_by_name['User'] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IncreaseUserCount = _reflection.GeneratedProtocolMessageType('IncreaseUserCount', (_message.Message,), {
  'DESCRIPTOR' : _INCREASEUSERCOUNT,
  '__module__' : 'protobuf.example_pb2'
  # @@protoc_insertion_point(class_scope:example.IncreaseUserCount)
  })
_sym_db.RegisterMessage(IncreaseUserCount)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'protobuf.example_pb2'
  # @@protoc_insertion_point(class_scope:example.User)
  })
_sym_db.RegisterMessage(User)


# @@protoc_insertion_point(module_scope)
