# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import general_pb2 as general__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payment.proto',
  package='payment',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rpayment.proto\x12\x07payment\x1a\rgeneral.proto\"\xc2\x01\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\"\n\x0crequest_info\x18\x03 \x01(\x0b\x32\x0c.RequestInfo\x12\x39\n\x0crequest_type\x18\x04 \x01(\x0e\x32#.payment.PaymentRequest.RequestType\".\n\x0bRequestType\x12\x07\n\x03PAY\x10\x00\x12\n\n\x06\x43\x41NCEL\x10\x01\x12\n\n\x06STATUS\x10\x02\"\\\n\rPaymentStatus\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x15\n\ractually_paid\x18\x02 \x01(\x08\x12\"\n\x0crequest_info\x18\x03 \x01(\x0b\x32\x0c.RequestInfob\x06proto3'
  ,
  dependencies=[general__pb2.DESCRIPTOR,])



_PAYMENTREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='payment.PaymentRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PAY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCEL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=190,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_PAYMENTREQUEST_REQUESTTYPE)


_PAYMENTREQUEST = _descriptor.Descriptor(
  name='PaymentRequest',
  full_name='payment.PaymentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='payment.PaymentRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='payment.PaymentRequest.order_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_info', full_name='payment.PaymentRequest.request_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_type', full_name='payment.PaymentRequest.request_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PAYMENTREQUEST_REQUESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=236,
)


_PAYMENTSTATUS = _descriptor.Descriptor(
  name='PaymentStatus',
  full_name='payment.PaymentStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='payment.PaymentStatus.order_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actually_paid', full_name='payment.PaymentStatus.actually_paid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_info', full_name='payment.PaymentStatus.request_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=330,
)

_PAYMENTREQUEST.fields_by_name['request_info'].message_type = general__pb2._REQUESTINFO
_PAYMENTREQUEST.fields_by_name['request_type'].enum_type = _PAYMENTREQUEST_REQUESTTYPE
_PAYMENTREQUEST_REQUESTTYPE.containing_type = _PAYMENTREQUEST
_PAYMENTSTATUS.fields_by_name['request_info'].message_type = general__pb2._REQUESTINFO
DESCRIPTOR.message_types_by_name['PaymentRequest'] = _PAYMENTREQUEST
DESCRIPTOR.message_types_by_name['PaymentStatus'] = _PAYMENTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaymentRequest = _reflection.GeneratedProtocolMessageType('PaymentRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTREQUEST,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payment.PaymentRequest)
  })
_sym_db.RegisterMessage(PaymentRequest)

PaymentStatus = _reflection.GeneratedProtocolMessageType('PaymentStatus', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTSTATUS,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payment.PaymentStatus)
  })
_sym_db.RegisterMessage(PaymentStatus)


# @@protoc_insertion_point(module_scope)
