apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: wdm-flink
spec:
  type: LoadBalancer
  selector:
    service: stock
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: wdm-flink
spec:
  type: LoadBalancer
  selector:
    service: payments
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: wdm-flink
spec:
  type: LoadBalancer
  selector:
    service: orders
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: wdm-flink
spec:
  type: LoadBalancer
  selector:
    service: users
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80