apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wdm-flink
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - name: frontend
        image: "gcr.io/wdm-statefun/api_endpoint"
        ports:
          - containerPort: 80
        env:
          - name: BROKER
            value: '***'
          - name: KEY
            value: '***'
          - name: SECRET
            value: '***'
        resources:
          requests:
            memory: "2048Mi"
            cpu: "3750m"
          limits:
            memory: "2048Mi"
            cpu: "4000m"