apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: wdm-flink
spec:
  type: LoadBalancer
  selector:
    service: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80