apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: wdm-flink
spec:
  selector:
    matchLabels:
      service: orders
  replicas: 1
  template:
    metadata:
      labels:
        service: orders
    spec:
      containers:
      - name: orders
        image: "gcr.io/wdm-statefun/order_service"
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1750m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"