apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: wdm-flink
spec:
  selector:
    matchLabels:
      service: payments
  replicas: 1
  template:
    metadata:
      labels:
        service: payments
    spec:
      containers:
      - name: payments
        image: "gcr.io/wdm-statefun/payment_service"
        ports:
          - containerPort: 80