apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  namespace: wdm-flink
spec:
  selector:
    matchLabels:
      service: stock
  replicas: 2
  template:
    metadata:
      labels:
        service: stock
    spec:
      containers:
      - name: stock
        image: "gcr.io/wdm-statefun/stock_service:380176b0"
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1750m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"