apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  namespace: wdm-flink
spec:
  selector:
    matchLabels:
      service: stock
  replicas: 1
  template:
    metadata:
      labels:
        service: stock
    spec:
      containers:
      - name: stock
        image: "gcr.io/wdm-statefun/stock_service"
        ports:
          - containerPort: 80