apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: wdm-flink
spec:
  selector:
    matchLabels:
      service: users
  replicas: 1
  template:
    metadata:
      labels:
        service: users
    spec:
      containers:
      - name: users
        image: "gcr.io/wdm-statefun/user_service"
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1750m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"