# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stock.proto',
  package='stock',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bstock.proto\x12\x05stock\"5\n\x08ItemData\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05price\x18\x02 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\"\x14\n\x05\x43ount\x12\x0b\n\x03num\x18\x01 \x01(\x04\"2\n\x11\x43reateItemRequest\x12\r\n\x05price\x18\x01 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"$\n\x12\x43reateItemResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3'
)




_ITEMDATA = _descriptor.Descriptor(
  name='ItemData',
  full_name='stock.ItemData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='stock.ItemData.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='stock.ItemData.price', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='stock.ItemData.amount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_COUNT = _descriptor.Descriptor(
  name='Count',
  full_name='stock.Count',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='stock.Count.num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=97,
)


_CREATEITEMREQUEST = _descriptor.Descriptor(
  name='CreateItemRequest',
  full_name='stock.CreateItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='stock.CreateItemRequest.price', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='stock.CreateItemRequest.amount', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=149,
)


_CREATEITEMRESPONSE = _descriptor.Descriptor(
  name='CreateItemResponse',
  full_name='stock.CreateItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='stock.CreateItemResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['ItemData'] = _ITEMDATA
DESCRIPTOR.message_types_by_name['Count'] = _COUNT
DESCRIPTOR.message_types_by_name['CreateItemRequest'] = _CREATEITEMREQUEST
DESCRIPTOR.message_types_by_name['CreateItemResponse'] = _CREATEITEMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemData = _reflection.GeneratedProtocolMessageType('ItemData', (_message.Message,), {
  'DESCRIPTOR' : _ITEMDATA,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.ItemData)
  })
_sym_db.RegisterMessage(ItemData)

Count = _reflection.GeneratedProtocolMessageType('Count', (_message.Message,), {
  'DESCRIPTOR' : _COUNT,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.Count)
  })
_sym_db.RegisterMessage(Count)

CreateItemRequest = _reflection.GeneratedProtocolMessageType('CreateItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEITEMREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.CreateItemRequest)
  })
_sym_db.RegisterMessage(CreateItemRequest)

CreateItemResponse = _reflection.GeneratedProtocolMessageType('CreateItemResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEITEMRESPONSE,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.CreateItemResponse)
  })
_sym_db.RegisterMessage(CreateItemResponse)


# @@protoc_insertion_point(module_scope)
