# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='users.proto',
  package='users',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0busers.proto\x12\x05users\"&\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x03\"\x14\n\x05\x43ount\x12\x0b\n\x03num\x18\x01 \x01(\x04\"\x13\n\x11\x43reateUserRequest\"$\n\x12\x43reateUserResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1e\n\x10\x43reateUserWithId\x12\n\n\x02id\x18\x01 \x01(\x04\"\x1d\n\x0f\x46indUserRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"\x1f\n\x11RemoveUserRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"3\n\x15SubtractCreditRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\".\n\x10\x41\x64\x64\x43reditRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"\xde\x01\n\x0bUserRequest\x12+\n\tfind_user\x18\x01 \x01(\x0b\x32\x16.users.FindUserRequestH\x00\x12/\n\x0bremove_user\x18\x02 \x01(\x0b\x32\x18.users.RemoveUserRequestH\x00\x12\x37\n\x0fsubtract_credit\x18\x03 \x01(\x0b\x32\x1c.users.SubtractCreditRequestH\x00\x12-\n\nadd_credit\x18\x04 \x01(\x0b\x32\x17.users.AddCreditRequestH\x00\x42\t\n\x07message\"#\n\x11\x41\x64\x64\x43reditResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"(\n\x16SubtractCreditResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"$\n\x12RemoveUserResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3'
)




_USERDATA = _descriptor.Descriptor(
  name='UserData',
  full_name='users.UserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='users.UserData.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='credit', full_name='users.UserData.credit', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=60,
)


_COUNT = _descriptor.Descriptor(
  name='Count',
  full_name='users.Count',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='users.Count.num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=82,
)


_CREATEUSERREQUEST = _descriptor.Descriptor(
  name='CreateUserRequest',
  full_name='users.CreateUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=103,
)


_CREATEUSERRESPONSE = _descriptor.Descriptor(
  name='CreateUserResponse',
  full_name='users.CreateUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='users.CreateUserResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=141,
)


_CREATEUSERWITHID = _descriptor.Descriptor(
  name='CreateUserWithId',
  full_name='users.CreateUserWithId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='users.CreateUserWithId.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=173,
)


_FINDUSERREQUEST = _descriptor.Descriptor(
  name='FindUserRequest',
  full_name='users.FindUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='users.FindUserRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=204,
)


_REMOVEUSERREQUEST = _descriptor.Descriptor(
  name='RemoveUserRequest',
  full_name='users.RemoveUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='users.RemoveUserRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=237,
)


_SUBTRACTCREDITREQUEST = _descriptor.Descriptor(
  name='SubtractCreditRequest',
  full_name='users.SubtractCreditRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='users.SubtractCreditRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='users.SubtractCreditRequest.amount', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=290,
)


_ADDCREDITREQUEST = _descriptor.Descriptor(
  name='AddCreditRequest',
  full_name='users.AddCreditRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='users.AddCreditRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='users.AddCreditRequest.amount', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=338,
)


_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='users.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='find_user', full_name='users.UserRequest.find_user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remove_user', full_name='users.UserRequest.remove_user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtract_credit', full_name='users.UserRequest.subtract_credit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_credit', full_name='users.UserRequest.add_credit', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='users.UserRequest.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=341,
  serialized_end=563,
)


_ADDCREDITRESPONSE = _descriptor.Descriptor(
  name='AddCreditResponse',
  full_name='users.AddCreditResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='users.AddCreditResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=600,
)


_SUBTRACTCREDITRESPONSE = _descriptor.Descriptor(
  name='SubtractCreditResponse',
  full_name='users.SubtractCreditResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='users.SubtractCreditResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=642,
)


_REMOVEUSERRESPONSE = _descriptor.Descriptor(
  name='RemoveUserResponse',
  full_name='users.RemoveUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='users.RemoveUserResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=644,
  serialized_end=680,
)

_USERREQUEST.fields_by_name['find_user'].message_type = _FINDUSERREQUEST
_USERREQUEST.fields_by_name['remove_user'].message_type = _REMOVEUSERREQUEST
_USERREQUEST.fields_by_name['subtract_credit'].message_type = _SUBTRACTCREDITREQUEST
_USERREQUEST.fields_by_name['add_credit'].message_type = _ADDCREDITREQUEST
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['find_user'])
_USERREQUEST.fields_by_name['find_user'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['remove_user'])
_USERREQUEST.fields_by_name['remove_user'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['subtract_credit'])
_USERREQUEST.fields_by_name['subtract_credit'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
_USERREQUEST.oneofs_by_name['message'].fields.append(
  _USERREQUEST.fields_by_name['add_credit'])
_USERREQUEST.fields_by_name['add_credit'].containing_oneof = _USERREQUEST.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['UserData'] = _USERDATA
DESCRIPTOR.message_types_by_name['Count'] = _COUNT
DESCRIPTOR.message_types_by_name['CreateUserRequest'] = _CREATEUSERREQUEST
DESCRIPTOR.message_types_by_name['CreateUserResponse'] = _CREATEUSERRESPONSE
DESCRIPTOR.message_types_by_name['CreateUserWithId'] = _CREATEUSERWITHID
DESCRIPTOR.message_types_by_name['FindUserRequest'] = _FINDUSERREQUEST
DESCRIPTOR.message_types_by_name['RemoveUserRequest'] = _REMOVEUSERREQUEST
DESCRIPTOR.message_types_by_name['SubtractCreditRequest'] = _SUBTRACTCREDITREQUEST
DESCRIPTOR.message_types_by_name['AddCreditRequest'] = _ADDCREDITREQUEST
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['AddCreditResponse'] = _ADDCREDITRESPONSE
DESCRIPTOR.message_types_by_name['SubtractCreditResponse'] = _SUBTRACTCREDITRESPONSE
DESCRIPTOR.message_types_by_name['RemoveUserResponse'] = _REMOVEUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserData = _reflection.GeneratedProtocolMessageType('UserData', (_message.Message,), {
  'DESCRIPTOR' : _USERDATA,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UserData)
  })
_sym_db.RegisterMessage(UserData)

Count = _reflection.GeneratedProtocolMessageType('Count', (_message.Message,), {
  'DESCRIPTOR' : _COUNT,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.Count)
  })
_sym_db.RegisterMessage(Count)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

CreateUserResponse = _reflection.GeneratedProtocolMessageType('CreateUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.CreateUserResponse)
  })
_sym_db.RegisterMessage(CreateUserResponse)

CreateUserWithId = _reflection.GeneratedProtocolMessageType('CreateUserWithId', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERWITHID,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.CreateUserWithId)
  })
_sym_db.RegisterMessage(CreateUserWithId)

FindUserRequest = _reflection.GeneratedProtocolMessageType('FindUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.FindUserRequest)
  })
_sym_db.RegisterMessage(FindUserRequest)

RemoveUserRequest = _reflection.GeneratedProtocolMessageType('RemoveUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.RemoveUserRequest)
  })
_sym_db.RegisterMessage(RemoveUserRequest)

SubtractCreditRequest = _reflection.GeneratedProtocolMessageType('SubtractCreditRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBTRACTCREDITREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.SubtractCreditRequest)
  })
_sym_db.RegisterMessage(SubtractCreditRequest)

AddCreditRequest = _reflection.GeneratedProtocolMessageType('AddCreditRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDCREDITREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.AddCreditRequest)
  })
_sym_db.RegisterMessage(AddCreditRequest)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

AddCreditResponse = _reflection.GeneratedProtocolMessageType('AddCreditResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDCREDITRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.AddCreditResponse)
  })
_sym_db.RegisterMessage(AddCreditResponse)

SubtractCreditResponse = _reflection.GeneratedProtocolMessageType('SubtractCreditResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBTRACTCREDITRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.SubtractCreditResponse)
  })
_sym_db.RegisterMessage(SubtractCreditResponse)

RemoveUserResponse = _reflection.GeneratedProtocolMessageType('RemoveUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.RemoveUserResponse)
  })
_sym_db.RegisterMessage(RemoveUserResponse)


# @@protoc_insertion_point(module_scope)
