# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rexample.proto\x12\x07\x65xample\"!\n\x11IncreaseUserCount\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"\"\n\x0f\x45xampleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0e\x45xampleRequest\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3'
)




_INCREASEUSERCOUNT = _descriptor.Descriptor(
  name='IncreaseUserCount',
  full_name='example.IncreaseUserCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.IncreaseUserCount.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='example.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='example.User.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=96,
)


_EXAMPLERESPONSE = _descriptor.Descriptor(
  name='ExampleResponse',
  full_name='example.ExampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example.ExampleResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=132,
)


_EXAMPLEREQUEST = _descriptor.Descriptor(
  name='ExampleRequest',
  full_name='example.ExampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example.ExampleRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['IncreaseUserCount'] = _INCREASEUSERCOUNT
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ExampleResponse'] = _EXAMPLERESPONSE
DESCRIPTOR.message_types_by_name['ExampleRequest'] = _EXAMPLEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IncreaseUserCount = _reflection.GeneratedProtocolMessageType('IncreaseUserCount', (_message.Message,), {
  'DESCRIPTOR' : _INCREASEUSERCOUNT,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.IncreaseUserCount)
  })
_sym_db.RegisterMessage(IncreaseUserCount)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.User)
  })
_sym_db.RegisterMessage(User)

ExampleResponse = _reflection.GeneratedProtocolMessageType('ExampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLERESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.ExampleResponse)
  })
_sym_db.RegisterMessage(ExampleResponse)

ExampleRequest = _reflection.GeneratedProtocolMessageType('ExampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLEREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.ExampleRequest)
  })
_sym_db.RegisterMessage(ExampleRequest)


# @@protoc_insertion_point(module_scope)
