name: Publish Docker image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
    branches:
    - master

env:
  STOCK_SERVICE_IMAGE: stock_service
  ORDER_SERVICE_IMAGE: order_service
  USER_SERVICE_IMAGE: user_service
  PAYMENT_SERVICE_IMAGE: payment_service
  ASYNC_ENDPOINT_IMAGE: api_endpoint
  FLINK_WORKER: flink_worker
  FLINK_MASTER: flink_master
  GCR_REGISTRY: gcr.io
  PROJECT_ID: wdm-statefun 

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Download statefun and build
        run: git clone https://github.com/apache/flink-statefun-docker && cd flink-statefun-docker/2.0.0 && docker build -t flink-statefun . && docker tag flink-statefun flink-statefun:2.0.0
      - name: Build images
        run: docker-compose build
      - name: Tag images
        run: |
          docker tag wdm-flink-statefun_stock-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$STOCK_SERVICE_IMAGE:${GITHUB_SHA::8}
          docker tag wdm-flink-statefun_users-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$USER_SERVICE_IMAGE:${GITHUB_SHA::8}
          docker tag wdm-flink-statefun_master:latest $GCR_REGISTRY/$PROJECT_ID/$FLINK_MASTER:${GITHUB_SHA::8}
          docker tag wdm-flink-statefun_worker:latest $GCR_REGISTRY/$PROJECT_ID/$FLINK_WORKER:${GITHUB_SHA::8}
          docker tag wdm-flink-statefun_api-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$ASYNC_ENDPOINT_IMAGE:${GITHUB_SHA::8}
          docker tag wdm-flink-statefun_orders-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$ORDER_SERVICE_IMAGE:${GITHUB_SHA::8}
          docker tag wdm-flink-statefun_payments-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$PAYMENT_SERVICE_IMAGE:${GITHUB_SHA::8}
          
          docker tag wdm-flink-statefun_stock-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$STOCK_SERVICE_IMAGE:latest
          docker tag wdm-flink-statefun_users-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$USER_SERVICE_IMAGE:latest
          docker tag wdm-flink-statefun_master:latest $GCR_REGISTRY/$PROJECT_ID/$FLINK_MASTER:latest
          docker tag wdm-flink-statefun_worker:latest $GCR_REGISTRY/$PROJECT_ID/$FLINK_WORKER:latest
          docker tag wdm-flink-statefun_api-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$ASYNC_ENDPOINT_IMAGE:latest
          docker tag wdm-flink-statefun_orders-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$ORDER_SERVICE_IMAGE:latest
          docker tag wdm-flink-statefun_payments-endpoint:latest $GCR_REGISTRY/$PROJECT_ID/$PAYMENT_SERVICE_IMAGE:latest
      - name: Push images
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} | base64 --decode --ignore-garbage > /tmp/key.json
          gcloud auth activate-service-account --quiet --key-file /tmp/key.json
          gcloud auth configure-docker --quiet
          
          docker push $GCR_REGISTRY/$PROJECT_ID/$STOCK_SERVICE_IMAGE:${GITHUB_SHA::8}
          docker push $GCR_REGISTRY/$PROJECT_ID/$STOCK_SERVICE_IMAGE:latest
          
          docker push $GCR_REGISTRY/$PROJECT_ID/$USER_SERVICE_IMAGE:${GITHUB_SHA::8}
          docker push $GCR_REGISTRY/$PROJECT_ID/$USER_SERVICE_IMAGE:latest
          
          docker push $GCR_REGISTRY/$PROJECT_ID/$FLINK_MASTER:${GITHUB_SHA::8}
          docker push $GCR_REGISTRY/$PROJECT_ID/$FLINK_MASTER:latest
          
          docker push $GCR_REGISTRY/$PROJECT_ID/$FLINK_WORKER:${GITHUB_SHA::8}
          docker push $GCR_REGISTRY/$PROJECT_ID/$FLINK_WORKER:latest
          
          docker push $GCR_REGISTRY/$PROJECT_ID/$ASYNC_ENDPOINT_IMAGE:${GITHUB_SHA::8}
          docker push $GCR_REGISTRY/$PROJECT_ID/$ASYNC_ENDPOINT_IMAGE:latest
          
          docker push $GCR_REGISTRY/$PROJECT_ID/$ORDER_SERVICE_IMAGE:${GITHUB_SHA::8}
          docker push $GCR_REGISTRY/$PROJECT_ID/$ORDER_SERVICE_IMAGE:latest
          
          docker push $GCR_REGISTRY/$PROJECT_ID/$PAYMENT_SERVICE_IMAGE:${GITHUB_SHA::8}
          docker push $GCR_REGISTRY/$PROJECT_ID/$PAYMENT_SERVICE_IMAGE:latest
